version: '3'
services:

  mysqldb:
    image: mysql:8
    container_name: mysql-simulacao-bd
    networks:
      - bd-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simulacao
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mq:
    image: rabbitmq:3
    container_name: rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bd-network

  app:
    image: gtbarbosa/simulacao-app
    container_name: simulacao-app
    restart: on-failure
    build: .
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - bd-network
    depends_on:
      - mysqldb
      - mq

networks:
  bd-network: