version: '3'
services:

  mysqldb:
    image: mysql:8
    container_name: mysql-simulacao-bd
    networks:
      - bd-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simulacao
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    image: gtbarbosa/simulacao-app
    container_name: simulacao-app
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - bd-network
    depends_on:
      - mysqldb

networks:
  bd-network: